'use strict';
/* =====================================================================
 * PFC API 契约定义（服务端）
 * 与前端 original/api-client.js 的 PFCAPI.api.contract() 结构一致，
 * GET /api/contract 对外暴露，供前端验证与文档对照（对齐《13-M1接口清单》）。
 * ===================================================================== */
module.exports = {
  auth: [
    ['devLogin', 'POST /api/auth/dev-login'],
    ['me', 'GET /api/auth/me'],
  ],
  reqs: [
    ['verificationWorkspace', 'GET /api/reqs/:id/verification-workspace'],
    ['testSuites', 'GET /api/reqs/:id/test-suites'],
    ['testSuite', 'GET /api/reqs/:id/test-suites/:sid'],
    ['createTestSuite', 'POST /api/reqs/:id/test-suites'],
    ['adoptTestSuite', 'POST /api/reqs/:id/test-suites/:sid/adopt'],
    ['deliveryBaselines', 'GET /api/reqs/:id/delivery-baselines'],
    ['deliveryBaseline', 'GET /api/reqs/:id/delivery-baselines/:bid'],
    ['createDeliveryBaseline', 'POST /api/reqs/:id/delivery-baselines'],
    ['testBatches', 'GET /api/reqs/:id/test-batches'],
    ['testBatch', 'GET /api/reqs/:id/test-batches/:bid'],
    ['createTestBatch', 'POST /api/reqs/:id/test-batches'],
    ['appendTestResults', 'POST /api/reqs/:id/test-batches/:bid/results'],
    ['completeTestBatch', 'POST /api/reqs/:id/test-batches/:bid/complete'],
    ['cancelTestBatch', 'POST /api/reqs/:id/test-batches/:bid/cancel'],
    ['defects', 'GET /api/reqs/:id/defects'],
    ['defect', 'GET /api/reqs/:id/defects/:did'],
    ['createDefect', 'POST /api/reqs/:id/defects'],
    ['resolveDefect', 'POST /api/reqs/:id/defects/:did/resolve'],
    ['retestDefect', 'POST /api/reqs/:id/defects/:did/retest'],
    ['productAcceptances', 'GET /api/reqs/:id/product-acceptances'],
    ['productAcceptance', 'GET /api/reqs/:id/product-acceptances/:aid'],
    ['createProductAcceptance', 'POST /api/reqs/:id/product-acceptances'],
    ['releaseInputs', 'GET /api/reqs/:id/release-inputs'],
    ['artifactWorkspace', 'GET /api/reqs/:id/artifact-workspace'],
    ['artifactGroups', 'GET /api/reqs/:id/artifact-groups'],
    ['artifactGroup', 'GET /api/reqs/:id/artifact-groups/:gid'],
    ['linkedArtifact', 'GET /api/reqs/:id/linked-artifacts/:vid'],
    ['artifactProposals', 'GET /api/reqs/:id/artifact-proposals'],
    ['artifactProposal', 'GET /api/reqs/:id/artifact-proposals/:pid'],
    ['createArtifactProposal', 'POST /api/reqs/:id/artifact-proposals'],
    [
      'adoptArtifactProposal',
      'POST /api/reqs/:id/artifact-proposals/:pid/adopt',
    ],
    [
      'rejectArtifactProposal',
      'POST /api/reqs/:id/artifact-proposals/:pid/reject',
    ],
    [
      'confirmBusiness',
      'POST /api/reqs/:id/artifact-groups/:gid/confirm-business',
    ],
    ['confirmDesign', 'POST /api/reqs/:id/artifact-groups/:gid/confirm-design'],
    ['stageInputs', 'GET /api/reqs/:id/stage-inputs'],
    ['list', 'GET /api/reqs'],
    ['create', 'POST /api/reqs'],
    ['get', 'GET /api/reqs/:id'],
    ['advanceStage', 'PATCH /api/reqs/:id/stage'],
    ['associateProject', 'PATCH /api/reqs/:id/project'],
    ['capOverrides', 'GET /api/reqs/:id/cap-overrides'],
    ['setCapOverrides', 'PUT /api/reqs/:id/cap-overrides'],
    ['versions', 'GET /api/reqs/:id/versions'],
    ['saveVersion', 'POST /api/reqs/:id/versions'],
    ['reviewVersion', 'POST /api/reqs/:id/versions/:vid/reviews'],
    ['replaceMaterial', 'POST /api/reqs/:id/materials/:mid/versions'],
    ['materialImpact', 'POST /api/reqs/:id/materials/:mid/impact'],
    ['materialContent', 'GET /api/reqs/:id/materials/:mid/content'],
    ['stopMessage', 'POST /api/reqs/:id/messages/:mid/stop'],
    ['messageDiff', 'POST /api/reqs/:id/messages/:mid/diff'],
    ['confirmVersion', 'POST /api/reqs/:id/versions/:vid/confirm'],
    ['addMaterial', 'POST /api/reqs/:id/materials'],
    ['answerQuestion', 'POST /api/reqs/:id/questions/:qid/answer'],
    ['messages', 'GET /api/reqs/:id/messages'],
    ['sendMessage', 'POST /api/reqs/:id/messages'],
  ],
  runs: [
    ['createRun', 'POST /api/runs'],
    ['lines', 'GET /api/runs/:id/lines'],
    ['planApprove', 'POST /api/runs/:id/plan-approve'],
    ['planReject', 'POST /api/runs/:id/plan-reject'],
    ['start', 'POST /api/runs/:id/start'],
    ['cancel', 'POST /api/runs/:id/cancel'],
    ['verify', 'POST /api/runs/:id/verify'],
    ['qualityGates', 'POST /api/runs/:id/quality-gates'],
    ['replay', 'GET /api/runs/:id/replay'],
    ['acquireLease', 'POST /api/leases/acquire'],
    ['handoffLease', 'POST /api/leases/handoff'],
  ],
  governance: [
    ['caps', 'GET /api/caps'],
    ['registerCap', 'POST /api/caps'],
    ['reviewCap', 'POST /api/caps/:id/review'],
    ['toggleCap', 'PATCH /api/caps/:id/toggle'],
    ['bindings', 'GET/PUT /api/bindings'],
    ['members', 'GET /api/members'],
    ['addMember', 'POST /api/members'],
    ['disableMember', 'DELETE /api/members/:uid'],
    ['exportAudit', 'GET /api/audit/export'],
    ['setRole', 'PATCH /api/members/:uid/role'],
    ['audit', 'GET /api/audit'],
    ['budget', 'GET /api/budgets/me'],
    ['knowledge', 'GET /api/knowledge'],
    ['addKnowledge', 'POST /api/knowledge'],
  ],
  release: [
    ['submit', 'POST /api/reqs/:id/releases'],
    ['approve', 'POST /api/releases/:id/approve'],
    ['reject', 'POST /api/releases/:id/reject'],
    ['execute', 'POST /api/releases/:id/execute'],
    ['rollback', 'POST /api/releases/:id/rollback'],
    ['cicd', 'POST /api/releases/:id/cicd'],
  ],
  notices: [
    ['list', 'GET /api/notices'],
    ['markRead', 'POST /api/notices/:id/read'],
    ['readAll', 'POST /api/notices/read-all'],
  ],
  projects: [
    ['list', 'GET /api/projects'],
    ['create', 'POST /api/projects'],
    ['get', 'GET /api/projects/:id'],
  ],
};
